# 14th April

In [1]:
import numpy as np

In [3]:
an_array = np.array([3,33,333])
an_array

array([  3,  33, 333])

In [4]:
type(an_array)

numpy.ndarray

In [5]:
an_array.shape

(3,)

In [6]:
print(an_array[0], an_array[1], an_array[2])

3 33 333


In [7]:
an_array[0] = 888
an_array

array([888,  33, 333])

## 2D Array

In [10]:
another = np.array([[11,12,13], [21,22,23]])
another

array([[11, 12, 13],
       [21, 22, 23]])

In [11]:
another.shape

(2, 3)

In [13]:
print(another[0,0], another[0,1], another[1,0])

11 12 21


## Functions

In [15]:
ax1 = np.zeros((2,2))
ax1

array([[0., 0.],
       [0., 0.]])

In [16]:
ax1 = np.full((2,2),9.0)
ax1

array([[9., 9.],
       [9., 9.]])

In [19]:
ax3 = np.eye(2,2)
ax3

array([[1., 0.],
       [0., 1.]])

In [25]:
ax4 = np.ones((1,2))
ax4

array([[1., 1.]])

In [26]:
ax4.shape

(1, 2)

In [27]:
ax4[0,0]

1.0

In [31]:
ax5 = np.random.random((2,2))
ax5

array([[0.00995698, 0.51152777],
       [0.80857882, 0.11979325]])

In [35]:
a1 = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a1

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

## Slicing

In [42]:
a_slice = a1[0:2,1:3]
a_slice

array([[12, 13],
       [22, 23]])

In [44]:
print('before : ', a1[0,1])
a_slice[0,0] = 1000
print('after : ', a1[0,1])

before :  12
after :  1000


In [48]:
a2 = np.array([[11,12,13,14], [21,22,23,24], [31,32,33,34]])
a2

array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [47]:
r1 = a2[1 , :]
print(r1, r1.shape)

[21 22 23 24] (4,)


In [50]:
r2 = a2[1:2 , :]
print(r2, r2.shape)

[[21 22 23 24]] (1, 4)


In [54]:
col_r1 = a2[:, 1]
col_r2 = a2[:, 1:2]

print(col_r1 , col_r1.shape)
print()
print(col_r2 , col_r2.shape)

[12 22 32] (3,)

[[12]
 [22]
 [32]] (3, 1)


In [57]:
a3 = np.array([[11,12,13], [21,22,23], [31,32,33]])
a3

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [68]:
col_indices = np.array([0,1,2])
print('Col Indices : ', col_indices)

row_indices = np.arange(3)
print('Row Indices : ', row_indices)

Col Indices :  [0 1 2]
Row Indices :  [0 1 2]


In [69]:
for row,col in zip(row_indices, col_indices):
    print(row, ",", col)

0 , 0
1 , 1
2 , 2


In [70]:
print('Values in array at those indices', a3[row_indices, col_indices])

Values in array at those indices [11 22 33]


In [73]:
a3[row_indices, col_indices] += 10000
a3

array([[20011,    12,    13],
       [   21, 20022,    23],
       [   31,    32, 20033]])

## Filtering

In [61]:
an_array2 = np.array([[11,12], [21,22], [31,32]])
an_array2

array([[11, 12],
       [21, 22],
       [31, 32]])

In [62]:
filter1 = (an_array2>15)
filter1

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [65]:
an_array2[filter1]

array([21, 22, 31, 32])

In [66]:
an_array2[an_array2>15]

array([21, 22, 31, 32])

In [76]:
an_array2[an_array2%2 ==0] += 1000
an_array2

array([[  11, 2012],
       [  21, 2022],
       [  31, 2032]])

# 15th April

## Data Types
* int, float, string, boolean

In [1]:
import numpy as np

In [2]:
ex1 = np.array([11,12])
print(ex1.dtype)

int32


In [3]:
ex2 = np.array([11.0,12.0])
print(ex2.dtype)

float64


In [4]:
ex3 = np.array([11,21], dtype=np.int64)
print(ex3.dtype)

int64


In [5]:
ex4 = np.array([11.1,12.7], dtype = np.int64)
print(ex4)
print(ex4.dtype)

[11 12]
int64


In [6]:
ex5 = np.array([11,21], dtype = np.float64)
print(ex5)
print(ex5.dtype)

[11. 21.]
float64


## Arithmetic Array Operations

In [7]:
x = np.array([[111,112], [121,122]])
y = np.array([[211.1,212.1], [211.1,222.2]])

print(x)
print(y)

[[111 112]
 [121 122]]
[[211.1 212.1]
 [211.1 222.2]]


In [8]:
#Add
print(x+y)
print()
print(np.add(x,y))

[[322.1 324.1]
 [332.1 344.2]]

[[322.1 324.1]
 [332.1 344.2]]


In [9]:
#Subtract
print(x-y)
print()
print(np.subtract(x,y))

[[-100.1 -100.1]
 [ -90.1 -100.2]]

[[-100.1 -100.1]
 [ -90.1 -100.2]]


In [10]:
#Multiply
print(x*y)
print()
print(np.multiply(x,y))

[[23432.1 23755.2]
 [25543.1 27108.4]]

[[23432.1 23755.2]
 [25543.1 27108.4]]


In [11]:
#Divide
print(x/y)
print()
print(np.divide(x,y))

[[0.52581715 0.52805281]
 [0.57318806 0.54905491]]

[[0.52581715 0.52805281]
 [0.57318806 0.54905491]]


In [12]:
#Sauareroot
print(np.sqrt(x))

[[10.53565375 10.58300524]
 [11.         11.04536102]]


In [13]:
#Exponential
print(np.exp(x))

[[1.60948707e+48 4.37503945e+48]
 [3.54513118e+52 9.63666567e+52]]


## Basic Statistical Operation

In [14]:
arr = 10* np.random.rand(2,2)
arr

array([[2.10163048, 9.50597247],
       [2.21989633, 2.50764406]])

In [15]:
arr.mean()

4.08378583465588

In [16]:
# mean along the row
arr.mean(axis = 1)

array([5.80380147, 2.3637702 ])

In [17]:
# mean along the column
arr.mean(axis = 0)

array([2.1607634 , 6.00680826])

In [18]:
# median along the row
np.median(arr, axis = 1)

array([5.80380147, 2.3637702 ])

In [19]:
# Sum of array
arr.sum()

16.33514333862352

## Sorting

In [20]:
unsorted = np.random.randn(10)
unsorted

array([-0.79072606,  0.5367118 ,  0.96410956, -0.48583124,  0.49566491,
       -1.15370003,  2.85569876, -0.04095383,  0.57569278,  1.43925154])

In [21]:
# create copy and sort
sorted = np.array(unsorted)
sorted.sort()

print (sorted)
print ()
print (unsorted)

[-1.15370003 -0.79072606 -0.48583124 -0.04095383  0.49566491  0.5367118
  0.57569278  0.96410956  1.43925154  2.85569876]

[-0.79072606  0.5367118   0.96410956 -0.48583124  0.49566491 -1.15370003
  2.85569876 -0.04095383  0.57569278  1.43925154]


In [22]:
# inplace sort
unsorted.sort()

print(unsorted)

[-1.15370003 -0.79072606 -0.48583124 -0.04095383  0.49566491  0.5367118
  0.57569278  0.96410956  1.43925154  2.85569876]


## Finding unique elements

In [23]:
a = np.array([1,23,4,5,51,5,5])
np.unique(a)

array([ 1,  4,  5, 23, 51])

In [24]:
s1 = np.array(['desk', 'chair', 'bulb'])
s2 = np.array(['lamp', 'bulb', 'chair'])

In [25]:
np.intersect1d(s1,s2)

array(['bulb', 'chair'], dtype='<U5')

In [26]:
np.union1d(s1,s2)

array(['bulb', 'chair', 'desk', 'lamp'], dtype='<U5')

In [27]:
np.setdiff1d(s1,s2)  # elements in s1 that are not in s2

array(['desk'], dtype='<U5')

In [28]:
np.in1d(s1,s2)

array([False,  True,  True])

## Broadcasting

In [29]:
start = np.zeros((4,3))
start

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
add_rows = np.array([1,0,2])

In [31]:
y = start + add_rows  # add to each row
y

array([[1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.],
       [1., 0., 2.]])

In [32]:
add_cols = np.array([[0,1,2,3]])
add_cols = add_cols.T  # Transpose
add_cols

array([[0],
       [1],
       [2],
       [3]])

In [33]:
z = start + add_cols  # add to each row
z

array([[0., 0., 0.],
       [1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.]])

In [34]:
add_scalar = np.array([1])
start + add_scalar

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
arrA = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
arrA

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [36]:
arrB = [0,1,0,2]
arrB

[0, 1, 0, 2]

In [37]:
arrA + arrB

array([[ 1,  3,  3,  6],
       [ 5,  7,  7, 10],
       [ 9, 11, 11, 14]])

## Speed test - Array vs List

In [4]:
from numpy import arange
from timeit import Timer

In [5]:
size = 1000000
timeits = 1000

In [6]:
nd_array = arange(size)
type(nd_array)

numpy.ndarray

In [7]:
timer_numpy = Timer("nd_array.sum()", "from __main__ import nd_array")

print("Time taken by numpy ndarray: %f seconds" % 
      (timer_numpy.timeit(timeits)/timeits))

Time taken by numpy ndarray: 0.000867 seconds


In [8]:
a_list = list(range(size))
type(a_list)

list

In [9]:
timer_list = Timer("sum(a_list)", "from __main__ import a_list")

print("Time taken by list: %f seconds" % 
      (timer_list.timeit(timeits)/timeits))

Time taken by list: 0.061117 seconds


# 19th April

## Binary Format

In [10]:
x = np.array([23.23,24.24])

In [11]:
np.save('an_array', x)

In [12]:
np.load('an_array.npy')

array([23.23, 24.24])

## Text Format

In [14]:
np.savetxt('array.txt', X=x, delimiter=',')

In [15]:
np.loadtxt('array.txt', delimiter=',')

array([23.23, 24.24])

## Additional common ndarray operations

In [16]:
#dot product of two matrices
x2d = np.array([[1,1],[1,1]])
y2d = np.array([[2,2],[2,2]])

print(x2d.dot(y2d))
print()
print(np.dot(x2d,y2d))

[[4 4]
 [4 4]]

[[4 4]
 [4 4]]


In [17]:
#inner product of two vectors
a1d = np.array([9,9])
b1d = np.array([10,10])

print(a1d.dot(b1d))
print()
print(np.dot(a1d,b1d))

180

180


In [18]:
#dot product of array & vectors

print(x2d.dot(a1d))
print()
print(np.dot(x2d,a1d))

[18 18]

[18 18]


## Sum

In [20]:
ex1 = np.array([[11,12],[21,22]])
print(np.sum(ex1))

66


In [21]:
print(np.sum(ex1, axis=0))  # columnwise sum

[32 34]


In [22]:
print(np.sum(ex1, axis=1))  # rowwise sum

[23 43]


## Elementwise Functions

In [24]:
x = np.random.randn(8)
x

array([ 0.30702977, -0.20481302,  1.19092468, -1.59769777, -0.87741622,
        0.24335814, -2.36624713, -1.02540471])

In [25]:
y = np.random.randn(8)
y

array([-0.37306753, -0.35620124,  0.45669691, -1.4504239 ,  0.97457443,
       -0.74330724, -0.65665079, -1.17226376])

In [26]:
np.maximum(x,y)

array([ 0.30702977, -0.20481302,  1.19092468, -1.4504239 ,  0.97457443,
        0.24335814, -0.65665079, -1.02540471])

## Reshape

In [31]:
arr = np.arange(20)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [106]:
arr.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [35]:
ex1 = np.array([[11,12],[21,22]])
ex1

array([[11, 12],
       [21, 22]])

In [37]:
ex1.T

array([[11, 21],
       [12, 22]])

## indexing using where()

In [38]:
x1 = np.array([1,2,3,4,5])
y1 = np.array([11,22,33,44,55])

filter = np.array([True, False,True, False,True])

In [40]:
out = np.where(filter,x1,y1)
out

array([ 1, 22,  3, 44,  5])

In [56]:
mat = np.random.rand(5,5)
mat

array([[0.64638483, 0.07444677, 0.6742851 , 0.67089332, 0.42491417],
       [0.34417044, 0.7090233 , 0.80858505, 0.30669463, 0.37337407],
       [0.26817584, 0.02178071, 0.04631955, 0.27519859, 0.04356562],
       [0.25886291, 0.64568382, 0.76108273, 0.68683606, 0.54636758],
       [0.90983064, 0.41887901, 0.44502094, 0.52650244, 0.7340336 ]])

In [57]:
np.where(mat>0.5 ,1000 ,-1)   # if mat>0.5, replace it with 1000 else replace it with -1

array([[1000,   -1, 1000, 1000,   -1],
       [  -1, 1000, 1000,   -1,   -1],
       [  -1,   -1,   -1,   -1,   -1],
       [  -1, 1000, 1000, 1000, 1000],
       [1000,   -1,   -1, 1000, 1000]])

## any or all

In [58]:
arr_bools = np.array([True, False,True,True, False])

In [61]:
arr_bools.any()

True

In [60]:
arr_bools.all()

False

In [63]:
y = np.random.normal(size = (1,5))
y

array([[ 1.63343841,  0.59053965,  1.01349263, -0.5186804 ,  3.21223488]])

In [65]:
z = np.random.randint(2,50,4)
z

array([40, 20, 33, 44])

In [95]:
np.random.permutation(z) # returns new ordering of elements in Z

array([40, 33, 44, 20])

In [77]:
np.random.uniform(size = 4) # uniform distribution

array([0.30178886, 0.31411568, 0.82477325, 0.06819618])

In [74]:
np.random.normal(size = 4) # normal distribution

array([ 0.6608637 , -0.36819873, -0.43390993, -1.30077969])

## Merging arrays

In [97]:
k = np.random.randint(low = 2 , high = 50, size = (2,2))
k

array([[27, 46],
       [24, 11]])

In [99]:
m = np.random.randint(low = 2 , high = 50, size = (2,2))
m

array([[ 4,  9],
       [22, 21]])

In [100]:
np.vstack((k,m))

array([[27, 46],
       [24, 11],
       [ 4,  9],
       [22, 21]])

In [101]:
np.hstack((k,m))

array([[27, 46,  4,  9],
       [24, 11, 22, 21]])

In [102]:
np.concatenate([k,m], axis = 0)  # axis = 0 > along column

array([[27, 46],
       [24, 11],
       [ 4,  9],
       [22, 21]])

In [105]:
np.concatenate([k,m], axis = 1) # axis = 1 > along row

array([[27, 46,  4,  9],
       [24, 11, 22, 21]])